{% set name = "pythresh" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythresh-{{ version }}.tar.gz
  sha256: d0a73a743e6db248929018e9c78fcd05f5fe5dae6d7f02bb603b9885583c781a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy >=1.13
    - pyod
    - python >={{ python_min }}
    - scikit-learn >=0.20.0
    - scipy >=1.3.1
    - six

test:
  imports:
    - pythresh
    - pythresh.thresholds
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/KulikDM/pythresh
  summary: A Python Toolbox for Outlier Detection Thresholding
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - KulikDM
