{% set name = "pythresh" %}
{% set version = "0.3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pythresh-{{ version }}.tar.gz
  sha256: 90a61563388337c379edb7f5c6ad5d270d4b450beb045e6c13965cdf105994cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base
    - numpy >=1.13
    - pyod
    - python >=3.7
    - scikit-learn >=0.20.0
    - scipy >=1.3.1
    - six

test:
  imports:
    - pythresh
    - pythresh.thresholds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KulikDM/pythresh
  summary: A Python Toolbox for Outlier Detection Thresholding
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - KulikDM
